server:
  port: 3000

spring:
  application:
    name: meta-data-test

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/meta_data_db
    username: dhkim1522
    password: 1022

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true

  mvc:
    converters:
      preferred-json-mapper: gson

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    sql: debug
#    web: debug


